"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
#import ez_setup
#ez_setup.use_setuptools()

from setuptools import setup

APP = ['./src/main.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': True,
    'packages': ["OpenGL",
                 "OpenGL_accelerate",
                 "processing",
                 "PySide2",
                 "PySide2.QtXml",
                 "PySide2.QtUiTools",
                 "shiboken2",
                 "scipy.special.cython_special"]
}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
